controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
contact_show:
    path: /contact
    controller: App\Controller\ContactMailController::showForm
    methods: [GET]

contact_submit:
    path: /contact
    controller: App\Controller\ContactMailController::submitForm
    methods: [POST]